services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - apil6

  api_l6:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    restart: always
    container_name: api_l6
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
    volumes:
      - ./public:/usr/src/app/public:rw
    networks:
      - webservices
      - apil6

networks:
  webservices:
    external: true
  apil6: